# Generated by Django 3.1.6 on 2021-02-20 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('body', models.CharField(db_index=True, default='У этого отделения нет описания', max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('body', models.CharField(blank=True, db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('body', models.CharField(db_index=True, default='У этой роли нет описания', max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(db_index=True, max_length=50, verbose_name='Отчество')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='user_workbench.department')),
                ('roles', models.ManyToManyField(blank=True, related_name='profile', to='user_workbench.UserRole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('body', models.CharField(db_index=True, default='У этой задачи нет описания', max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.CharField(max_length=350)),
                ('time_limitation', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='user_workbench.userprofile')),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='assigned_tasks', to='user_workbench.UserProfile')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user_workbench.taskstatus')),
                ('super_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='user_workbench.task')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_remains', models.TimeField()),
                ('remind_interval', models.TimeField()),
                ('reminder_type', models.CharField(db_index=True, default='standart', max_length=50)),
                ('settings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_reminders', to='user_workbench.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_department', to='user_workbench.userprofile'),
        ),
        migrations.AddField(
            model_name='department',
            name='super_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_department', to='user_workbench.department'),
        ),
    ]
