# Generated by Django 3.1.6 on 2021-02-24 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_limitation',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.date(9999, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.CharField(blank=True, default='У этой задачи нет описания', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
