# Generated by Django 3.1.6 on 2021-02-24 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0002_auto_20210225_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(9999, 1, 1, 1, 1, 1, tzinfo=utc), null=True),
        ),
    ]
