# Generated by Django 3.1.6 on 2021-02-28 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0003_auto_20210225_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(9999, 1, 1, 1, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible_users',
            field=models.ManyToManyField(related_name='assigned_tasks', to='user_workbench.UserProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('dn', 'Выполнено'), ('ns', 'Не начато'), ('nw', 'Нет ответственных'), ('ip', 'В процессе выполнения'), ('hs', 'Есть незаконченные подзадачи')], default='ns', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='super_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_tasks', to='user_workbench.task'),
        ),
    ]
