# Generated by Django 3.1.6 on 2021-03-01 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0004_auto_20210228_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(9999, 1, 1, 1, 1, 1)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('nw', 'Нет ответственных'), ('ns', 'Не начато'), ('ip', 'В процессе выполнения'), ('hs', 'Есть незаконченные подзадачи'), ('dn', 'Выполнено'), ('ch', 'Проверено'), ('cn', 'Отменено')], default='ns', max_length=2),
        ),
    ]
