# Generated by Django 3.1.6 on 2021-03-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0005_auto_20210301_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.CharField(blank=True, default='У этой задачи нет описания', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
