# Generated by Django 3.1.6 on 2021-03-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0007_auto_20210301_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='chief',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slave_department', to='user_workbench.userprofile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible_users',
            field=models.ManyToManyField(related_name='assigned_tasks', to='user_workbench.UserProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nw', 'Нет ответственных'), ('ns', 'Не начато'), ('ip', 'В процессе выполнения'), ('hs', 'Есть незаконченные подзадачи'), ('dn', 'Выполнено'), ('ch', 'Проверено'), ('cn', 'Отменено')], default='ns', max_length=2),
        ),
    ]
