# Generated by Django 3.1.6 on 2021-03-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0008_auto_20210304_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['second_name']},
        ),
        migrations.AddField(
            model_name='task',
            name='justification',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='task',
            table='user_workbench_task',
        ),
    ]
