# Generated by Django 3.1.6 on 2021-03-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0011_auto_20210316_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='closure_time',
            new_name='closure_datetime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
    ]
