# Generated by Django 3.1.6 on 2021-03-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0012_auto_20210317_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nw', 'Нет ответственных'), ('ns', 'Не начато'), ('ip', 'В процессе выполнения'), ('hs', 'Есть подзадачи'), ('dn', 'Выполнено'), ('ch', 'Проверено'), ('cn', 'Отменено')], default='ns', max_length=2),
        ),
    ]
