# Generated by Django 3.1.6 on 2021-03-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0013_auto_20210318_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
