# Generated by Django 3.1.6 on 2021-03-21 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0015_auto_20210320_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessage',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_log', to='user_workbench.task'),
        ),
    ]
