# Generated by Django 3.1.6 on 2021-03-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0016_infomessage_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomessage',
            name='receiver',
        ),
        migrations.AddField(
            model_name='infomessage',
            name='receivers',
            field=models.ManyToManyField(related_name='received_messages', to='user_workbench.UserProfile'),
        ),
    ]
