# Generated by Django 3.1.6 on 2021-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0017_auto_20210321_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomessage',
            name='message',
            field=models.CharField(db_index=True, default='Нет описания', max_length=350),
        ),
    ]
