# Generated by Django 3.1.6 on 2021-03-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_workbench', '0019_auto_20210323_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chief',
            field=models.BooleanField(default=False),
        ),
    ]
